config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'highlights#index'

  get 'highlights', to: 'highlights#index', as: :highlights
  get 'backend', to: 'highlights#backend', as: :backend

  scope :highlights do
    get 'new', to: 'highlights#new', as: :new_highlight
    get 'edit/:id', to: 'highlights#edit', as: :edit_highlight
    post 'create', to: 'highlights#create', as: :create_highlight
    get 'backend', to: 'highlights#backend', as: :backend_highlights
    patch 'update/:id', to: 'highlights#update', as: :update_highlight
    delete 'delete/:id', to: 'highlights#destroy', as: :delete_highlight
  end

  get 'education', to: 'education#index', as: :education

  scope :education do
    get 'backend', to: 'education#backend', as: :backend_education

    scope :qualification do
      get 'new', to: 'education#new_qualification', as: :new_qualification
      post 'create', to: 'education#create_qualification', as: :create_qualification
      get 'show/:id', to: 'education#show_qualification', as: :show_qualification
      get 'edit/:id', to: 'education#edit_qualification', as: :edit_qualification
      patch 'update/:id', to: 'education#update_qualification', as: :update_qualification
      delete 'delete/:id', to: 'education#destroy_qualification', as: :delete_qualification
    end

    scope :year do
      get 'new/:qualification', to: 'education#new_year', as: :new_year
      post 'create/:qualification', to: 'education#create_year', as: :create_year
      get 'show/:id', to: 'education#show_year', as: :show_year
      get 'edit/:id', to: 'education#edit_year', as: :edit_year
      patch 'update/:id', to: 'education#update_year', as: :update_year
      delete 'delete/:id', to: 'education#destroy_year', as: :delete_year
    end

    scope :unit do
      get 'new/:year', to: 'education#new_unit', as: :new_unit
      post 'create/:year', to: 'education#create_unit', as: :create_unit
      get 'show/:id', to: 'education#show_unit', as: :show_unit
      get 'edit/:id', to: 'education#edit_unit', as: :edit_unit
      patch 'update/:id', to: 'education#update_unit', as: :update_unit
      delete 'delete/:id', to: 'education#destroy_unit', as: :delete_unit
    end
  end

  get 'profile', to: 'intro#backend', as: :profile

  scope :profile do
    scope :information do
      get 'new', to: 'intro#new_info', as: :new_info
      post 'create', to: 'intro#create_info', as: :create_info
      get 'edit/:id', to: 'intro#edit_info', as: :edit_info
      patch 'update/:id', to: 'intro#update_info', as: :update_info
      delete 'delete/:id', to: 'intro#destroy_info', as: :delete_info
    end

    scope :social_link do
      get 'new', to: 'intro#new_social', as: :new_social
      post 'create', to: 'intro#create_social', as: :create_social
      get 'edit/:id', to: 'intro#edit_social', as: :edit_social
      patch 'update/:id', to: 'intro#update_social', as: :update_social
      delete 'delete/:id', to: 'intro#destroy_social', as: :delete_social
    end
  end
end

app/models/highlight.rb
# frozen_string_literal: true

class Highlight < ApplicationRecord
  validates_presence_of :title, :organisation, :start_date, :description
end

app/controllers/highlights_controller.rb
# frozen_string_literal: true

class HighlightsController < ApplicationController
  layout 'backend', only: %i[backend show edit update destroy]

  before_action :set_highlight, only: %i[show edit update destroy]
  before_action :set_highlights, only: %i[index backend]

  http_basic_authenticate_with name: ENV['USERNAME'], password: ENV['PASSWORD'], only: %i[backend new edit]

  def index
    render 'frontend/highlights/index'
  end

  def backend
    render 'backend/highlights/index'
  end

  def new
    @highlight = Highlight.new

    render 'backend/highlights/new'
  end

  def edit
    render 'backend/highlights/edit'
  end

  def create
    @highlight = Highlight.new(highlight_params)

    respond_to do |format|
      if @highlight.save
        format.html { redirect_to backend_highlights_path, notice: 'highlight created' }
      else
        format.html { redirect_to backend_highlights_path, notice: 'failed to create' }
      end
    end
  end

  def update
    respond_to do |format|
      if @highlight.update(highlight_params)
        format.html { redirect_to backend_highlights_path, notice: 'highlight updated' }
      else
        format.html { redirect_to backend_highlights_path, notice: 'failed to update' }
      end
    end
  end

  def destroy
    @highlight.destroy
    respond_to do |format|
      format.html { redirect_to backend_highlights_path, notice: 'highlight removed' }
    end
  end

  private

  def set_highlights
    @highlights = Highlight.all
  end

  def set_highlight
    @highlight = Highlight.find(params[:id])
  end

  def highlight_params
    params.require(:highlight).permit(:title, :organisation, :start_date, :end_date, :description, :url)
  end
end

app/helpers/highlight_helper.rb
module HighlightHelper
end

app/views/backend/highlights/_highlight.html.erb
<div class="experience margin-b-50">
  <h4><%= highlight.title %></h4>
  <h5><%= highlight.organisation %></h5>
  <h6 class="font-lite-black margin-t-10"><%= duration_for(highlight) %></h6>
  <p class="margin-tb-10"><%= highlight.description %></p>
  <%= link_to 'more info', highlight.url, class: 'focused-link' unless highlight.url.empty? %>
  <%= link_to 'edit', edit_highlight_path(highlight), class: 'focused-link' %>
  <span class="or">or</span>
  <%= link_to 'remove', delete_highlight_path(highlight), method: :delete, class: 'focused-link-danger', data: { confirm: 'Are you sure? This action can not be undone.' }%>
</div>

app/views/backend/highlights/edit.html.erb
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <%= page_title(title: 'Edit Highlight') %>
      </div>

      <div class="col-lg-8">
        <%= form_with(model: @highlight, url: update_highlight_path) do |form| %>

          <div class="form-group">
            <label>Job Title / Qualificiation:</label><span class="font-red">*</span>
            <%= form.text_field :title, class: 'form-control', placeholder: 'Accountant or Bachelors Degree', required: true %>
          </div>

          <div class="form-group">
            <label>Organisation:</label><span class="font-red">*</span>
            <%= form.text_field :organisation, class: 'form-control', placeholder: 'Smith & Sons or Exeter University', required: true %>
          </div>

          <div class="form-row">
            <div class="form-group col-md-6">
              <label>Start Date</label><span class="font-red">*</span>
              <%= form.text_field :start_date, type: 'date', class: 'form-control', required: true%>
            </div>

            <div class="form-group col-md-6">
              <label>End Date (or leave blank)</label>
              <%= form.text_field :end_date, type: 'date', class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <label>Description:</label><span class="font-red">*</span>
            <%= form.text_area :description, class: 'form-control', placeholder: 'Type here...', rows: 4, required: true %>
          </div>

          <div class="form-group">
            <label>URL: (optional)</label>
            <%= form.text_field :url, class: 'form-control', placeholder: 'http://url/page' %>
          </div>

          <%= form.submit 'submit', class: 'focused-button' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/backend/highlights/index.html.erb
<section class="experience-section section">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="heading">
          <h3>Experience</h3>
          <h6 class="font-lite-black">highlights</h6>
          <%= link_to 'new', new_highlight_path, class: 'focused-link' %>
        </div>
      </div>

      <div class="col-lg-8">
        <div class="experience-wrapper">
          <% @highlights.each do |highlight| %>
            <%= render 'backend/highlights/highlight', highlight: highlight%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/backend/highlights/new.html.erb
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <%= page_title(title: 'New Highlight') %>
      </div>

      <div class="col-lg-8">
        <%= form_with(model: @highlight, url: create_highlight_path) do |form| %>

          <div class="form-group">
            <label>Job Title / Qualificiation:</label><span class="font-red">*</span>
            <%= form.text_field :title, class: 'form-control', placeholder: 'Accountant or Bachelors Degree', required: true %>
          </div>

          <div class="form-group">
            <label>Organisation:</label><span class="font-red">*</span>
            <%= form.text_field :organisation, class: 'form-control', placeholder: 'Smith & Sons or Exeter University', required: true %>
          </div>

          <div class="form-row">
            <div class="form-group col-md-6">
              <label>Start Date</label><span class="font-red">*</span>
              <%= form.text_field :start_date, type: 'date', class: 'form-control', required: true%>
            </div>

            <div class="form-group col-md-6">
              <label>End Date (or leave blank)</label>
              <%= form.text_field :end_date, type: 'date', class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <label>Description:</label><span class="font-red">*</span>
            <%= form.text_area :description, class: 'form-control', placeholder: 'Type here...', rows: 4, required: true %>
          </div>

          <div class="form-group">
            <label>URL: (optional)</label>
            <%= form.text_field :url, class: 'form-control', placeholder: 'http://url/page' %>
          </div>

          <%= form.submit 'submit', class: 'focused-button' %>
        <% end %>
      </div>
    </div>
  </div>
</section>