config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'highlights#index'

  get 'highlights', to: 'highlights#index', as: :highlights
  get 'backend', to: 'highlights#backend', as: :backend

  scope :highlights do
    get 'new', to: 'highlights#new', as: :new_highlight
    get 'edit/:id', to: 'highlights#edit', as: :edit_highlight
    post 'create', to: 'highlights#create', as: :create_highlight
    get 'backend', to: 'highlights#backend', as: :backend_highlights
    patch 'update/:id', to: 'highlights#update', as: :update_highlight
    delete 'delete/:id', to: 'highlights#destroy', as: :delete_highlight
  end

  get 'education', to: 'education#index', as: :education

  scope :education do
    get 'backend', to: 'education#backend', as: :backend_education

    scope :qualification do
      get 'new', to: 'education#new_qualification', as: :new_qualification
      post 'create', to: 'education#create_qualification', as: :create_qualification
      get 'show/:id', to: 'education#show_qualification', as: :show_qualification
      get 'edit/:id', to: 'education#edit_qualification', as: :edit_qualification
      patch 'update/:id', to: 'education#update_qualification', as: :update_qualification
      delete 'delete/:id', to: 'education#destroy_qualification', as: :delete_qualification
    end

    scope :year do
      get 'new/:qualification', to: 'education#new_year', as: :new_year
      post 'create/:qualification', to: 'education#create_year', as: :create_year
      get 'show/:id', to: 'education#show_year', as: :show_year
      get 'edit/:id', to: 'education#edit_year', as: :edit_year
      patch 'update/:id', to: 'education#update_year', as: :update_year
      delete 'delete/:id', to: 'education#destroy_year', as: :delete_year
    end

    scope :unit do
      get 'new/:year', to: 'education#new_unit', as: :new_unit
      post 'create/:year', to: 'education#create_unit', as: :create_unit
      get 'show/:id', to: 'education#show_unit', as: :show_unit
      get 'edit/:id', to: 'education#edit_unit', as: :edit_unit
      patch 'update/:id', to: 'education#update_unit', as: :update_unit
      delete 'delete/:id', to: 'education#destroy_unit', as: :delete_unit
    end
  end

  get 'profile', to: 'intro#backend', as: :profile

  scope :profile do
    scope :information do
      get 'new', to: 'intro#new_info', as: :new_info
      post 'create', to: 'intro#create_info', as: :create_info
      get 'edit/:id', to: 'intro#edit_info', as: :edit_info
      patch 'update/:id', to: 'intro#update_info', as: :update_info
      delete 'delete/:id', to: 'intro#destroy_info', as: :delete_info
    end

    scope :social_link do
      get 'new', to: 'intro#new_social', as: :new_social
      post 'create', to: 'intro#create_social', as: :create_social
      get 'edit/:id', to: 'intro#edit_social', as: :edit_social
      patch 'update/:id', to: 'intro#update_social', as: :update_social
      delete 'delete/:id', to: 'intro#destroy_social', as: :delete_social
    end
  end
end

app/models/qualification.rb
# frozen_string_literal: true

class Qualification < ApplicationRecord
  has_and_belongs_to_many :years
end

app/controllers/education_controller.rb
# frozen_string_literal: true

class EducationController < ApplicationController
  layout 'backend', only: %i[backend show_qualification edit_qualification new_qualification new_year edit_year new_unit edit_unit]

  before_action :set_qualifications, only: %i[index backend]
  before_action :set_qualification, only: %i[show_qualification edit_qualification update_qualification destroy_qualification]
  before_action :set_year, only: %i[edit_year update_year destroy_year]
  before_action :set_unit, only: %i[edit_unit update_unit destroy_unit]

  http_basic_authenticate_with name: ENV['USERNAME'], password: ENV['PASSWORD'],
                               only: %i[backend new_qualification new_year new_unit]

  def index
    render 'frontend/education/index'
  end

  def backend
    render 'backend/education/index'
  end

  def show_qualification
    render 'backend/education/qualification/show'
  end

  def new_qualification
    @qualification = Qualification.new

    render 'backend/education/qualification/new'
  end

  def create_qualification
    @qualification = Qualification.new(qualification_params)

    respond_to do |format|
      if @qualification.save
        format.html { redirect_to show_qualification_path(@qualification), notice: 'You can now add more details' }
      else
        format.html { redirect_to backend_education_path, alert: 'Something went wrong' }
      end
    end
  end

  def edit_qualification
    render 'backend/education/qualification/edit'
  end

  def update_qualification
    respond_to do |format|
      if @qualification.update(qualification_params)
        format.html { redirect_to show_qualification_path(@qualification), notice: 'Qualification updated' }
      else
        format.html { redirect_to backend_education_path, notice: 'Something went wrong' }
      end
    end
  end

  def destroy_qualification
    @qualification.destroy

    redirect_to backend_education_path, notice: 'Qualification deleted'
  end

  def new_year
    @year = Year.new

    render 'backend/education/year/new'
  end

  def create_year
    @year = Year.new(year_params)

    @qualification = Qualification.find(params[:qualification])

    respond_to do |format|
      if @year.save
        @qualification.years << @year
        format.html { redirect_to show_qualification_path(@qualification), notice: 'You can now add more details' }
      else
        format.html { redirect_to backend_education_path, alert: 'Something went wrong' }
      end
    end
  end

  def edit_year
    render 'backend/education/year/edit'
  end

  def update_year
    respond_to do |format|
      if @year.update(year_params)
        format.html { redirect_to show_qualification_path(@year.qualifications.first), notice: 'Qualification updated' }
      else
        format.html { redirect_to backend_education_path, notice: 'Something went wrong' }
      end
    end
  end

  def destroy_year
    @qualification = @year.qualifications.first
    @year.destroy

    redirect_to show_qualification_path(@qualification), notice: 'Year deleted'
  end

  def new_unit
    @unit = Unit.new

    render 'backend/education/unit/new'
  end

  def create_unit
    @unit = Unit.new(unit_params)
    @year = Year.find(params[:year])

    respond_to do |format|
      if @unit.save
        @year.units << @unit
        format.html { redirect_to show_qualification_path(@year.qualifications.first), notice: 'You can now add more details' }
      else
        format.html { redirect_to backend_education_path, alert: 'Something went wrong' }
      end
    end
  end

  def edit_unit
    render 'backend/education/unit/edit'
  end

  def update_unit
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to show_qualification_path(@unit.years.first.qualifications.first), notice: 'Qualification updated' }
      else
        format.html { redirect_to backend_education_path, notice: 'Something went wrong' }
      end
    end
  end

  def destroy_unit
    @qualification = @unit.years.first.qualifications.first
    @unit.destroy

    redirect_to show_qualification_path(@qualification), notice: 'Unit deleted'
  end

  private

  def qualification_params
    params.require(:qualification).permit(:title, :organisation)
  end

  def set_qualification
    @qualification = Qualification.find(params[:id])
  end

  def set_qualifications
    @qualifications = Qualification.all
  end

  def year_params
    params.require(:year).permit(:title, :grade)
  end

  def set_year
    @year = Year.find(params[:id])
  end

  def unit_params
    params.require(:unit).permit(:unit, :grade, :description)
  end

  def set_unit
    @unit = Unit.find(params[:id])
  end
end

app/views/backend/education/qualification/edit.html.erb
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <%= page_title(title: 'Update Qualification', subtitle: 'Update qualification details') %>
      </div>

      <div class="col-lg-8">
        <%= form_with(model: @qualification, url: update_qualification_path) do |form| %>

          <div class="form-group">
            <label>Qualificiation Title:</label><span class="font-red">*</span>
            <%= form.text_field :title, class: 'form-control', placeholder: 'i.e. Bachelors Degree', required: true %>
          </div>

          <div class="form-group">
            <label>Organisation:</label><span class="font-red">*</span>
            <%= form.text_field :organisation, class: 'form-control', placeholder: 'i.e. Exeter University', required: true %>
          </div>

          <%= form.submit 'update', class: 'focused-button' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/backend/education/qualification/new.html.erb
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <%= page_title(title: 'New Qualification', subtitle: 'Add your degree') %>
      </div>

      <div class="col-lg-8">
        <%= form_with(model: @qualification, url: create_qualification_path) do |form| %>

          <div class="form-group">
            <label>Qualificiation Title:</label><span class="font-red">*</span>
            <%= form.text_field :title, class: 'form-control', placeholder: 'i.e. Bachelors Degree', required: true %>
          </div>

          <div class="form-group">
            <label>Organisation:</label><span class="font-red">*</span>
            <%= form.text_field :organisation, class: 'form-control', placeholder: 'i.e. Exeter University', required: true %>
          </div>

          <%= form.submit 'submit', class: 'focused-button' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/backend/education/qualification/show.html.erb
<section class="experience-section section">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <%= page_title(title: @qualification.title, subtitle: @qualification.organisation) %>
        <%= link_to 'Update Qualifcation Details', edit_qualification_path(@qualification), class: 'focused-link' %><hr>
        <%= link_to 'Delete Qualification', delete_qualification_path(@qualification), method: :delete, class: 'focused-link-danger', data: { confirm: 'Are you sure? This action can not be undone.' } %>

      </div>

      <div class="col-lg-8">
        <% @qualification.years.each do |year| %>
          <div class="experience margin-b-50">
            <h4>
              <%= year.title %>
              <small class="font-blue">
                <%= year.grade %>
                <%= link_to 'edit', edit_year_path(year), class: 'focused-link' %> <span class="or">or</span>
                <%= link_to 'remove', delete_year_path(year), method: :delete, class: 'focused-link-danger', data: { confirm: 'Are you sure? This action can not be undone.' } %>
              </small>
            </h4>

            <% year.units.each do |unit| %>
              <h5><%= unit.unit %><small class="font-lightblue"> <%= unit.grade %></small></h5>
              <p class="margin-tb-10"><%= unit.description %></p>

              <%= link_to 'edit', edit_unit_path(unit), class: 'focused-link' %> <span class="or">or</span>
              <%= link_to 'remove', delete_unit_path(unit), method: :delete, class: 'focused-link-danger', data: { confirm: 'Are you sure? This action can not be undone.' } %>

              <hr>
            <% end %>

            <%= link_to 'Add Unit', new_unit_path(year), class: 'focused-link' %>
          </div>
        <% end %>
        <%= link_to 'Add Academic Year', new_year_path(@qualification), class: 'focused-link' %>
      </div>
    </div>
  </div>
</section>