config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'highlights#index'

  get 'highlights', to: 'highlights#index', as: :highlights
  get 'backend', to: 'highlights#backend', as: :backend

  scope :highlights do
    get 'new', to: 'highlights#new', as: :new_highlight
    get 'edit/:id', to: 'highlights#edit', as: :edit_highlight
    post 'create', to: 'highlights#create', as: :create_highlight
    get 'backend', to: 'highlights#backend', as: :backend_highlights
    patch 'update/:id', to: 'highlights#update', as: :update_highlight
    delete 'delete/:id', to: 'highlights#destroy', as: :delete_highlight
  end

  get 'education', to: 'education#index', as: :education

  scope :education do
    get 'backend', to: 'education#backend', as: :backend_education

    scope :qualification do
      get 'new', to: 'education#new_qualification', as: :new_qualification
      post 'create', to: 'education#create_qualification', as: :create_qualification
      get 'show/:id', to: 'education#show_qualification', as: :show_qualification
      get 'edit/:id', to: 'education#edit_qualification', as: :edit_qualification
      patch 'update/:id', to: 'education#update_qualification', as: :update_qualification
      delete 'delete/:id', to: 'education#destroy_qualification', as: :delete_qualification
    end

    scope :year do
      get 'new/:qualification', to: 'education#new_year', as: :new_year
      post 'create/:qualification', to: 'education#create_year', as: :create_year
      get 'show/:id', to: 'education#show_year', as: :show_year
      get 'edit/:id', to: 'education#edit_year', as: :edit_year
      patch 'update/:id', to: 'education#update_year', as: :update_year
      delete 'delete/:id', to: 'education#destroy_year', as: :delete_year
    end

    scope :unit do
      get 'new/:year', to: 'education#new_unit', as: :new_unit
      post 'create/:year', to: 'education#create_unit', as: :create_unit
      get 'show/:id', to: 'education#show_unit', as: :show_unit
      get 'edit/:id', to: 'education#edit_unit', as: :edit_unit
      patch 'update/:id', to: 'education#update_unit', as: :update_unit
      delete 'delete/:id', to: 'education#destroy_unit', as: :delete_unit
    end
  end

  get 'profile', to: 'intro#backend', as: :profile

  scope :profile do
    scope :information do
      get 'new', to: 'intro#new_info', as: :new_info
      post 'create', to: 'intro#create_info', as: :create_info
      get 'edit/:id', to: 'intro#edit_info', as: :edit_info
      patch 'update/:id', to: 'intro#update_info', as: :update_info
      delete 'delete/:id', to: 'intro#destroy_info', as: :delete_info
    end

    scope :social_link do
      get 'new', to: 'intro#new_social', as: :new_social
      post 'create', to: 'intro#create_social', as: :create_social
      get 'edit/:id', to: 'intro#edit_social', as: :edit_social
      patch 'update/:id', to: 'intro#update_social', as: :update_social
      delete 'delete/:id', to: 'intro#destroy_social', as: :delete_social
    end
  end
end

app/models/social.rb
class Social < ApplicationRecord
end

app/controllers/intro_controller.rb
# frozen_string_literal: true

class IntroController < ApplicationController
  layout 'backend'

  before_action :set_info, only: %i[edit_info update_info]
  before_action :set_social, only: %i[edit_social update_social destroy_social]

  http_basic_authenticate_with name: ENV['USERNAME'], password: ENV['PASSWORD']

  def backend
    @info = Info.all
    @socials = Social.all

    render 'backend/intro/index'
  end

  def new_info
    @info = Info.new

    render 'backend/intro/info/new'
  end

  def create_info
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to profile_path, notice: 'Created intro item' }
      else
        format.html { redirect_to profile_path, alert: 'Something went wrong' }
      end
    end
  end

  def edit_info
    render 'backend/intro/info/edit'
  end

  def update_info
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to profile_path, notice: 'Information updated' }
      else
        format.html { redirect_to profile_path, notice: 'Something went wrong' }
      end
    end
  end

  def new_social
    @social = Social.new

    render 'backend/intro/social/new'
  end

  def create_social
    @social = Social.new(social_params)

    respond_to do |format|
      if @social.save
        format.html { redirect_to profile_path, notice: 'Created intro item' }
      else
        format.html { redirect_to profile_path, alert: 'Something went wrong' }
      end
    end
  end

  def edit_social
    render 'backend/intro/social/edit'
  end

  def update_social
    respond_to do |format|
      if @social.update(social_params)
        format.html { redirect_to profile_path, notice: 'Information updated' }
      else
        format.html { redirect_to profile_path, notice: 'Something went wrong' }
      end
    end
  end

  def destroy_social
    @social.destroy

    redirect_to profile_path, notice: 'Social icon deleted.'
  end

  private

  def info_params
    params.require(:info).permit(:entity, :text_value)
  end

  def social_params
    params.require(:social).permit(:entity, :icon, :url)
  end

  def set_info
    @info = Info.find(params[:id])
  end

  def set_social
    @social = Social.find(params[:id])
  end
end

app/helpers/intro_helper.rb
# frozen_string_literal: true

module IntroHelper
  def name
    info = Info.where(entity: 'name').first

    return '' if info.nil?

    info.text_value
  end

  def position
    info = Info.where(entity: 'position').first

    return '' if info.nil?

    info.text_value
  end

  def social_icons
    Social.all
  end
end

app/views/backend/intro/social/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Entity</th>
      <th scope="col" colspan=2>Icon</th>
      <th scope="col">Url</th>
      <th scope="col" colspan=2>Manage</th>
    </tr>
  </thead>

  <tbody>
   <% @socials.each do |social| %>
    <tr>
      <td><%= social.entity %></td>
      <td><i class="<%= social.icon %>"></td>
      <td><%= social.icon %></i></td>
      <td><%= social.url %></td>
      <td><%= link_to 'edit', edit_social_path(social), class: 'focused-link' %></td>
      <td><%= link_to 'remove', delete_social_path(social), method: :delete, class: 'focused-link-danger', data: { confirm: 'Are you sure? This action can not be undone.' }%></td>
    </tr>
   <% end %>
  </tbody>
</table>

app/views/backend/intro/social/edit.html.erb
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <%= page_title(title: 'New Social Icon', subtitle: 'Add links with fa icons.') %>
      </div>

      <div class="col-lg-8">
        <%= form_with(model: @social, url: update_social_path) do |form| %>

          <div class="form-group">
            <label>Entity:</label><span class="font-red">*</span>
            <%= form.text_field :entity, class: 'form-control', placeholder: 'LinkedIn', required: true %>
          </div>

          <div class="form-group">
            <label>Icon:</label><span class="font-red">*</span>
            <%= form.text_field :icon, class: 'form-control', placeholder: 'fa fa-linkedin', required: true %>
          </div>

          <p>For help choosing a social icon please head to: <a href="https://fontawesome.com/icons?d=gallery" target="_blank">fontawesome.com</a></p>
          <hr>

          <div class="form-group">
            <label>URL:</label><span class="font-red">*</span>
            <%= form.text_field :url, class: 'form-control', placeholder: 'https://yourlinkedinurl.co.uk', required: true %>
          </div>

          <%= form.submit 'submit', class: 'focused-button' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/backend/intro/social/new.html.erb
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <%= page_title(title: 'Edit Social Icon', subtitle: 'Add links with fa icons.') %>
      </div>

      <div class="col-lg-8">
        <%= form_with(model: @social, url: create_social_path) do |form| %>

          <div class="form-group">
            <label>Entity:</label><span class="font-red">*</span>
            <%= form.text_field :entity, class: 'form-control', placeholder: 'LinkedIn', required: true %>
          </div>

          <div class="form-group">
            <label>Icon:</label><span class="font-red">*</span>
            <%= form.text_field :icon, class: 'form-control', placeholder: 'fa fa-linkedin', required: true %>
          </div>

          <p>For help choosing a social icon please head to: <a href="https://fontawesome.com/icons?d=gallery" target="_blank">fontawesome.com</a></p>
          <hr>

          <div class="form-group">
            <label>URL:</label><span class="font-red">*</span>
            <%= form.text_field :url, class: 'form-control', placeholder: 'https://yourlinkedinurl.co.uk', required: true %>
          </div>

          <%= form.submit 'submit', class: 'focused-button' %>
        <% end %>
      </div>
    </div>
  </div>
</section>